export const NAME = "Marcus Holloway";
export const JOB = "Hacker and Vigilante at";
export const COMPANY = "DedSec, Inc";
export const TEXT_RULES = "Rules and Regulations before becoming a pleb on DedSec";
export const POST_TEXT = "Can you people post appropriate stuff here? Please...";
export const VIEWS = "5,300 VIEWS";
export const REACTIONS = "1,324 REACTIONS";
export const RULES = "Rules and Regulations...";
export const WEEK = "1w";
export const ANNOUNCEMENT = "Announcement";
export const DISCUSSION = "Discussion";
export const HELP_RULES = "Can you people help with...?";
export const THREE = "3";
export const GUIDE_TEXT = "I am new here, any guides to use this thing?";
export const ADMINS = "Admin";
export const MODERATORS = "Moderators";
export const FREEBIE_TEXT = "Just here for the freebies LOL";
export const ONE = "1"
export const NEW_TEXT = " I am new here, any...?"
export const JUST_HERE = "Just here for..."
export const TWO = "2"
export const FOUR = "4"
